## post request

POST http://localhost:3000/users
Content-Type:application/json


{
  "firstName": "kajoma",
  "lastName": "devi",
  "email": "kajoma-devi-12@gmail.com",
  "password": "12qwQW@?,,"
}


POST http://localhost:3000/users/create-many
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6Imtham9tYUBnbWFpbC5jb20iLCJpYXQiOjE3ODE4NDYzNTEsImV4cCI6MTc4MTg0OTk1MSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.n2amUsSxOxowNJ8zxDT-L50upCG5yq9zLtx9VZELcmc
{
  "users": [
    {
      "firstName":"amrit",
      "lastName":"Kumar",
      "email":"amrit001@gmail.com",
      "password":"12qwQW@?,,"
    },
     {
      "firstName":"kajoma",
      "lastName":"devi",
      "email":"kajoma@gmail.com",
      "password":"12qwQW@?,,"
    }
  ]
}
