POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJpYXQiOjE3ODIxMDc3MDIsImV4cCI6MTc4MjE5NDEwMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.BBR7j-4Npn0ReZShycOSfEtkXCi7PIx07aOzpSTqahc"
}


